/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Carlito Morales
 */
public class NewCuestionario extends javax.swing.JFrame {
    static short sumaResp=0;
    /**
     * Creates new form NewCuestionario
     */
    public NewCuestionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel3.setVisible(false);
        SetImageLabel(Imagen1,"src/Imagenes/1.png");
        SetImageLabel(Imagen2,"src/Imagenes/2.jpg");
        SetImageLabel(Imagen3,"src/Imagenes/3.png");
        SetImageLabel(Imagen4,"src/Imagenes/4.jpg");
        SetImageLabel(Imagen5,"src/Imagenes/5.png");
        SetImageLabel(Imagen6,"src/Imagenes/6.jpg");
        SetImageLabel(Imagen7,"src/Imagenes/7.jpg");
        SetImageLabel(Imagen8,"src/Imagenes/8.jpg");
        SetImageLabel(Imagen9,"src/Imagenes/9.png");
        SetImageLabel(Imagen10,"src/Imagenes/10.jpg");
        SetImageLabel(jLabel14,"src/Imagenes/0.jpg");
        jLabel14.setVisible(false);
        this.pack();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        Grupo2 = new javax.swing.ButtonGroup();
        Grupo3 = new javax.swing.ButtonGroup();
        Grupo4 = new javax.swing.ButtonGroup();
        Grupo5 = new javax.swing.ButtonGroup();
        Grupo6 = new javax.swing.ButtonGroup();
        Grupo7 = new javax.swing.ButtonGroup();
        Grupo8 = new javax.swing.ButtonGroup();
        Grupo9 = new javax.swing.ButtonGroup();
        Grupo10 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Imagen2 = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JLabel();
        Imagen3 = new javax.swing.JLabel();
        Imagen4 = new javax.swing.JLabel();
        Imagen5 = new javax.swing.JLabel();
        aP1 = new javax.swing.JRadioButton();
        bP1 = new javax.swing.JRadioButton();
        cP1 = new javax.swing.JRadioButton();
        dP1 = new javax.swing.JRadioButton();
        dP2 = new javax.swing.JRadioButton();
        aP2 = new javax.swing.JRadioButton();
        cP2 = new javax.swing.JRadioButton();
        bP2 = new javax.swing.JRadioButton();
        aP3 = new javax.swing.JRadioButton();
        bP3 = new javax.swing.JRadioButton();
        cP3 = new javax.swing.JRadioButton();
        dP3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aP4 = new javax.swing.JRadioButton();
        bP4 = new javax.swing.JRadioButton();
        dP5 = new javax.swing.JRadioButton();
        aP5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        bP5 = new javax.swing.JRadioButton();
        cP5 = new javax.swing.JRadioButton();
        aP6 = new javax.swing.JRadioButton();
        bP6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cP6 = new javax.swing.JRadioButton();
        dP6 = new javax.swing.JRadioButton();
        aP7 = new javax.swing.JRadioButton();
        bP7 = new javax.swing.JRadioButton();
        cP7 = new javax.swing.JRadioButton();
        dP7 = new javax.swing.JRadioButton();
        aP8 = new javax.swing.JRadioButton();
        bP8 = new javax.swing.JRadioButton();
        cP8 = new javax.swing.JRadioButton();
        dP8 = new javax.swing.JRadioButton();
        aP9 = new javax.swing.JRadioButton();
        bP9 = new javax.swing.JRadioButton();
        aP10 = new javax.swing.JRadioButton();
        bP10 = new javax.swing.JRadioButton();
        cP10 = new javax.swing.JRadioButton();
        dP10 = new javax.swing.JRadioButton();
        Imagen6 = new javax.swing.JLabel();
        Imagen7 = new javax.swing.JLabel();
        Imagen8 = new javax.swing.JLabel();
        Imagen9 = new javax.swing.JLabel();
        Imagen10 = new javax.swing.JLabel();
        ResultadosB = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        calificacion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUESTIONARIO");
        setBackground(new java.awt.Color(153, 153, 255));
        setIconImages(null);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel11.setFont(new java.awt.Font("Berkshire Swash", 3, 48)); // NOI18N
        jLabel11.setText("Cuestionario");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        aP1.setBackground(new java.awt.Color(153, 204, 255));
        Grupo1.add(aP1);
        aP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP1.setText("a) AWT");
        aP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP1ActionPerformed(evt);
            }
        });

        bP1.setBackground(new java.awt.Color(153, 204, 255));
        Grupo1.add(bP1);
        bP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP1.setText("b) Swing");
        bP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP1ActionPerformed(evt);
            }
        });

        cP1.setBackground(new java.awt.Color(153, 204, 255));
        Grupo1.add(cP1);
        cP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP1.setText("c) Graphics");
        cP1.setToolTipText("");
        cP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP1ActionPerformed(evt);
            }
        });

        dP1.setBackground(new java.awt.Color(153, 204, 255));
        Grupo1.add(dP1);
        dP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP1.setText("d) ActionListener");
        dP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP1ActionPerformed(evt);
            }
        });

        dP2.setBackground(new java.awt.Color(153, 204, 255));
        Grupo2.add(dP2);
        dP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP2.setText("d) radioMenu");
        dP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP2ActionPerformed(evt);
            }
        });

        aP2.setBackground(new java.awt.Color(153, 204, 255));
        Grupo2.add(aP2);
        aP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP2.setText("a) JMenu");
        aP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP2ActionPerformed(evt);
            }
        });

        cP2.setBackground(new java.awt.Color(153, 204, 255));
        Grupo2.add(cP2);
        cP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP2.setText("c) barMenu");
        cP2.setToolTipText("");
        cP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP2ActionPerformed(evt);
            }
        });

        bP2.setBackground(new java.awt.Color(153, 204, 255));
        Grupo2.add(bP2);
        bP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP2.setText("b) menuItem");
        bP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP2ActionPerformed(evt);
            }
        });

        aP3.setBackground(new java.awt.Color(153, 204, 255));
        Grupo3.add(aP3);
        aP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP3.setText("a) JTextArea");
        aP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP3ActionPerformed(evt);
            }
        });

        bP3.setBackground(new java.awt.Color(153, 204, 255));
        Grupo3.add(bP3);
        bP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP3.setText("b) JTextFieldHide");
        bP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP3ActionPerformed(evt);
            }
        });

        cP3.setBackground(new java.awt.Color(153, 204, 255));
        Grupo3.add(cP3);
        cP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP3.setText("c) JTextField");
        cP3.setToolTipText("");
        cP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP3ActionPerformed(evt);
            }
        });

        dP3.setBackground(new java.awt.Color(153, 204, 255));
        Grupo3.add(dP3);
        dP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP3.setText("d) JPasswordField");
        dP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("1. ¿A qué clase pertenecen los componentes de menú y texto?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("2.- ¿Cómo se le llama al componente que se encuentra en casi todos los menús?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("3.- ¿Con que componente se ingresan contraseñas?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("4.- ¿Los menús pueden tener iconos?");

        aP4.setBackground(new java.awt.Color(153, 204, 255));
        Grupo4.add(aP4);
        aP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP4.setText("a) Verdadero");
        aP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP4ActionPerformed(evt);
            }
        });

        bP4.setBackground(new java.awt.Color(153, 204, 255));
        Grupo4.add(bP4);
        bP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP4.setText("b) Falso");
        bP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP4ActionPerformed(evt);
            }
        });

        dP5.setBackground(new java.awt.Color(153, 204, 255));
        Grupo5.add(dP5);
        dP5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP5.setText("d) JTextField");
        dP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP5ActionPerformed(evt);
            }
        });

        aP5.setBackground(new java.awt.Color(153, 204, 255));
        Grupo5.add(aP5);
        aP5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP5.setText("a) JTextArea");
        aP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("5.- ¿En que componente se puede implementar HTML para dar estilos?");

        bP5.setBackground(new java.awt.Color(153, 204, 255));
        Grupo5.add(bP5);
        bP5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP5.setText("b) JTextFieldHide");
        bP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP5ActionPerformed(evt);
            }
        });

        cP5.setBackground(new java.awt.Color(153, 204, 255));
        Grupo5.add(cP5);
        cP5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP5.setText("c) JEditorPane");
        cP5.setToolTipText("");
        cP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP5ActionPerformed(evt);
            }
        });

        aP6.setBackground(new java.awt.Color(153, 204, 255));
        Grupo6.add(aP6);
        aP6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP6.setText("a) JEditorPane");
        aP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP6ActionPerformed(evt);
            }
        });

        bP6.setBackground(new java.awt.Color(153, 204, 255));
        Grupo6.add(bP6);
        bP6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP6.setText("b) JTextFieldHide");
        bP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("6.- ¿Qué componente permite ingresar múltiples líneas de texto?");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("7.- ¿Qué menú se abre al presionar click derecho?");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("8.- ¿Qué componente permite la entrada de texto con un formato en específico?");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("9.- Un menú de RadioButton tiene que agruparlos ya que no se hace de forma automática:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("10.- ¿Qué componente de menú puede seleccionar y deseleccionar opciones?");

        cP6.setBackground(new java.awt.Color(153, 204, 255));
        Grupo6.add(cP6);
        cP6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP6.setText("c) JEditorPane");
        cP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP6ActionPerformed(evt);
            }
        });

        dP6.setBackground(new java.awt.Color(153, 204, 255));
        Grupo6.add(dP6);
        dP6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP6.setText("d) JTextArea");
        dP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP6ActionPerformed(evt);
            }
        });

        aP7.setBackground(new java.awt.Color(153, 204, 255));
        Grupo7.add(aP7);
        aP7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP7.setText("a) JMenu");
        aP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP7ActionPerformed(evt);
            }
        });

        bP7.setBackground(new java.awt.Color(153, 204, 255));
        Grupo7.add(bP7);
        bP7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP7.setText("b) JPopupMenu");
        bP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP7ActionPerformed(evt);
            }
        });

        cP7.setBackground(new java.awt.Color(153, 204, 255));
        Grupo7.add(cP7);
        cP7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP7.setText("c) menuItem");
        cP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP7ActionPerformed(evt);
            }
        });

        dP7.setBackground(new java.awt.Color(153, 204, 255));
        Grupo7.add(dP7);
        dP7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP7.setText("d) JRadioMenu");
        dP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP7ActionPerformed(evt);
            }
        });

        aP8.setBackground(new java.awt.Color(153, 204, 255));
        Grupo8.add(aP8);
        aP8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP8.setText("a) JEditorTextPane");
        aP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP8ActionPerformed(evt);
            }
        });

        bP8.setBackground(new java.awt.Color(153, 204, 255));
        Grupo8.add(bP8);
        bP8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP8.setText("b) JTextArea");
        bP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP8ActionPerformed(evt);
            }
        });

        cP8.setBackground(new java.awt.Color(153, 204, 255));
        Grupo8.add(cP8);
        cP8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP8.setText("c) JFormatTextField");
        cP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP8ActionPerformed(evt);
            }
        });

        dP8.setBackground(new java.awt.Color(153, 204, 255));
        Grupo8.add(dP8);
        dP8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP8.setText("d) JMataJevers");
        dP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP8ActionPerformed(evt);
            }
        });

        aP9.setBackground(new java.awt.Color(153, 204, 255));
        Grupo9.add(aP9);
        aP9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP9.setText("a) Verdadero");
        aP9.setToolTipText("");
        aP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP9ActionPerformed(evt);
            }
        });

        bP9.setBackground(new java.awt.Color(153, 204, 255));
        Grupo9.add(bP9);
        bP9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP9.setText("b) Falso");
        bP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP9ActionPerformed(evt);
            }
        });

        aP10.setBackground(new java.awt.Color(153, 204, 255));
        Grupo10.add(aP10);
        aP10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aP10.setText("a) JCheckBox");
        aP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aP10ActionPerformed(evt);
            }
        });

        bP10.setBackground(new java.awt.Color(153, 204, 255));
        Grupo10.add(bP10);
        bP10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bP10.setText("b) JRadioButton");
        bP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bP10ActionPerformed(evt);
            }
        });

        cP10.setBackground(new java.awt.Color(153, 204, 255));
        Grupo10.add(cP10);
        cP10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cP10.setText("c) JTextPapu");
        cP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cP10ActionPerformed(evt);
            }
        });

        dP10.setBackground(new java.awt.Color(153, 204, 255));
        Grupo10.add(dP10);
        dP10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dP10.setText("d) JFloppaJavaGod");
        dP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dP10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(aP7)
                    .addComponent(bP7)
                    .addComponent(cP7)
                    .addComponent(dP7)
                    .addComponent(aP6)
                    .addComponent(bP6)
                    .addComponent(cP6)
                    .addComponent(dP6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dP1)
                                .addComponent(cP1)
                                .addComponent(aP1)
                                .addComponent(bP1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aP3)
                                .addComponent(bP3)
                                .addComponent(cP3)
                                .addComponent(dP3))
                            .addGap(228, 228, 228)
                            .addComponent(Imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Imagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cP8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dP8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aP8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bP8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cP10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dP10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(aP10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bP10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Imagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(Imagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Imagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aP9)
                                .addComponent(bP9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aP5)
                                .addComponent(bP5)
                                .addComponent(cP5)
                                .addComponent(dP5))
                            .addGap(228, 228, 228)
                            .addComponent(Imagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aP4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(bP4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aP2)
                                .addComponent(bP2)
                                .addComponent(dP2)
                                .addComponent(cP2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP1))
                    .addComponent(Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(cP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP2)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bP2))
                            .addComponent(Imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP3)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP4)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Imagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Imagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Imagen5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aP6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP6))
                    .addComponent(Imagen6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aP7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP7))
                    .addComponent(Imagen7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aP8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP8))
                    .addComponent(Imagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aP9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bP9))
                    .addComponent(Imagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aP10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bP10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cP10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP10))
                    .addComponent(Imagen10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        ResultadosB.setBackground(new java.awt.Color(255, 204, 153));
        ResultadosB.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ResultadosB.setText("RESULTADOS");
        ResultadosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadosBActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("DM Serif Display", 1, 18)); // NOI18N
        jLabel12.setText("EQUIPO 3");

        jLabel13.setFont(new java.awt.Font("DM Serif Display", 2, 18)); // NOI18N
        jLabel13.setText("Tema Equipo 4");

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        calificacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(calificacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ResultadosB)
                                    .addGap(217, 217, 217))))
                        .addGap(5, 5, 5)))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultadosB)
                    .addComponent(calificacion))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ResultadosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadosBActionPerformed
        // TODO add your handkling code here:
        short Sum = Conteo();
        calificacion.setText("Calificacion: "+((Sum*100)/10));
        grafica();
        jScrollPane2.setVisible(false);
        jPanel3.setVisible(true);
        ResultadosB.setVisible(false);
        if(Sum>=7){
            jLabel14.setVisible(true);
        }
        this.pack();
    }//GEN-LAST:event_ResultadosBActionPerformed

    private void dP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP10ActionPerformed

    private void cP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP10ActionPerformed

    private void bP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP10ActionPerformed

    private void aP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP10ActionPerformed

    private void bP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP9ActionPerformed

    private void aP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP9ActionPerformed

    private void dP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP8ActionPerformed

    private void cP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP8ActionPerformed

    private void bP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP8ActionPerformed

    private void aP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP8ActionPerformed

    private void dP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP7ActionPerformed

    private void cP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP7ActionPerformed

    private void bP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP7ActionPerformed

    private void aP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP7ActionPerformed

    private void dP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP6ActionPerformed

    private void cP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP6ActionPerformed

    private void bP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP6ActionPerformed

    private void aP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP6ActionPerformed

    private void cP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP5ActionPerformed

    private void bP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP5ActionPerformed

    private void aP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP5ActionPerformed

    private void dP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP5ActionPerformed

    private void bP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP4ActionPerformed

    private void aP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP4ActionPerformed

    private void dP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP3ActionPerformed

    private void cP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP3ActionPerformed

    private void bP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP3ActionPerformed

    private void aP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP3ActionPerformed

    private void bP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP2ActionPerformed

    private void cP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP2ActionPerformed

    private void aP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP2ActionPerformed

    private void dP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP2ActionPerformed

    private void dP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dP1ActionPerformed

    private void cP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cP1ActionPerformed

    private void bP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bP1ActionPerformed

    private void aP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aP1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCuestionario().setVisible(true);
            }
        });
        
    }
    
    public short Conteo(){
        sumaResp=0;
        if(bP1.isSelected()){
            sumaResp+=1;
        }
        if(bP2.isSelected()){
            sumaResp+=1;
        }
        if(dP3.isSelected()) {
            sumaResp+=1;
        }
        if(aP4.isSelected()) {
            sumaResp+=1;
        }
        if(cP5.isSelected()) {
            sumaResp+=1;
        }
        if(dP6.isSelected()) {
            sumaResp+=1;
        }
        if(bP7.isSelected()) {
            sumaResp+=1;
        }
        if(cP8.isSelected()) {
            sumaResp+=1;
        }
        if(bP9.isSelected()) {
            sumaResp+=1;
        }
        if(aP10.isSelected()) {
            sumaResp+=1;
        }
                
        return sumaResp;
    }

        public static void grafica(){ 
        DefaultPieDataset datos=new DefaultPieDataset(); 
        datos.setValue("CORRECTA",sumaResp);
        datos.setValue("INCORRECTA",(10-sumaResp));
        
        JFreeChart resultados=ChartFactory.createPieChart("RESULTADOS", datos, true, true, false);
        
        ChartPanel panel=new ChartPanel(resultados);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,400));
        
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(panel,BorderLayout.NORTH);
        
    }
        
    private void SetImageLabel(JLabel label,String root){
        ImageIcon image=new ImageIcon(root);
        Icon icon=new ImageIcon(image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.ButtonGroup Grupo10;
    private javax.swing.ButtonGroup Grupo2;
    private javax.swing.ButtonGroup Grupo3;
    private javax.swing.ButtonGroup Grupo4;
    private javax.swing.ButtonGroup Grupo5;
    private javax.swing.ButtonGroup Grupo6;
    private javax.swing.ButtonGroup Grupo7;
    private javax.swing.ButtonGroup Grupo8;
    private javax.swing.ButtonGroup Grupo9;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Imagen10;
    private javax.swing.JLabel Imagen2;
    private javax.swing.JLabel Imagen3;
    private javax.swing.JLabel Imagen4;
    private javax.swing.JLabel Imagen5;
    private javax.swing.JLabel Imagen6;
    private javax.swing.JLabel Imagen7;
    private javax.swing.JLabel Imagen8;
    private javax.swing.JLabel Imagen9;
    private javax.swing.JButton ResultadosB;
    private javax.swing.JRadioButton aP1;
    private javax.swing.JRadioButton aP10;
    private javax.swing.JRadioButton aP2;
    private javax.swing.JRadioButton aP3;
    private javax.swing.JRadioButton aP4;
    private javax.swing.JRadioButton aP5;
    private javax.swing.JRadioButton aP6;
    private javax.swing.JRadioButton aP7;
    private javax.swing.JRadioButton aP8;
    private javax.swing.JRadioButton aP9;
    private javax.swing.JRadioButton bP1;
    private javax.swing.JRadioButton bP10;
    private javax.swing.JRadioButton bP2;
    private javax.swing.JRadioButton bP3;
    private javax.swing.JRadioButton bP4;
    private javax.swing.JRadioButton bP5;
    private javax.swing.JRadioButton bP6;
    private javax.swing.JRadioButton bP7;
    private javax.swing.JRadioButton bP8;
    private javax.swing.JRadioButton bP9;
    private javax.swing.JRadioButton cP1;
    private javax.swing.JRadioButton cP10;
    private javax.swing.JRadioButton cP2;
    private javax.swing.JRadioButton cP3;
    private javax.swing.JRadioButton cP5;
    private javax.swing.JRadioButton cP6;
    private javax.swing.JRadioButton cP7;
    private javax.swing.JRadioButton cP8;
    private javax.swing.JLabel calificacion;
    private javax.swing.JRadioButton dP1;
    private javax.swing.JRadioButton dP10;
    private javax.swing.JRadioButton dP2;
    private javax.swing.JRadioButton dP3;
    private javax.swing.JRadioButton dP5;
    private javax.swing.JRadioButton dP6;
    private javax.swing.JRadioButton dP7;
    private javax.swing.JRadioButton dP8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
